// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316152941_AddSucursalTelefono")]
    partial class AddSucursalTelefono
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.ArqueoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("numeric");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalManualEsperado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalRealContado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalVentasEsperado")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ArqueosCaja");
                });

            modelBuilder.Entity("Core.Entities.ArqueoCajaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArqueoCajaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MetodoPagoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoEsperado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoReal")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArqueoCajaId");

                    b.HasIndex("MetodoPagoId");

                    b.ToTable("ArqueosCajaDetalle");
                });

            modelBuilder.Entity("Core.Entities.AtributoConfiguracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Grupo");

                    b.HasIndex("TenantId", "Grupo", "Valor")
                        .IsUnique();

                    b.ToTable("AtributosConfiguracion", (string)null);
                });

            modelBuilder.Entity("Core.Entities.BilleteraVirtual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("BilleterasVirtuales");
                });

            modelBuilder.Entity("Core.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EsquemaAtributosJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Core.Entities.CertificadoDigital", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyVaultReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CertificadosDigitales");
                });

            modelBuilder.Entity("Core.Entities.ChequeTercero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emisor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCobro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NumeroCheque")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PagoProveedorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PagoProveedorId");

                    b.ToTable("ChequesTerceros");
                });

            modelBuilder.Entity("Core.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CondicionIva")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferenciasJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SaldoAFavor")
                        .HasColumnType("numeric");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Core.Entities.ClientePrendaEnCurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioReferencia")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductoManualNombre")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("VarianteManualNombre")
                        .HasColumnType("text");

                    b.Property<Guid?>("VarianteProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VarianteProductoId");

                    b.ToTable("PrendasClientesEnCurso");
                });

            modelBuilder.Entity("Core.Entities.Comprobante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CAE")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIva")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalNeto")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("VencimientoCAE")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("Core.Entities.DistribucionPagoFactura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacturaProveedorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoAsignado")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PagoProveedorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FacturaProveedorId");

                    b.HasIndex("PagoProveedorId");

                    b.ToTable("DistribucionesPagosFacturas");
                });

            modelBuilder.Entity("Core.Entities.EstadoDispositivoPwa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DispositivoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemsPendientesSubida")
                        .HasColumnType("integer");

                    b.Property<string>("NombreDispositivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UltimaVezOnline")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EstadosDispositivosPwa");
                });

            modelBuilder.Entity("Core.Entities.FacturaProveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentoUrl")
                        .HasColumnType("text");

                    b.Property<int>("EstadoProcesamiento")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadatosRawJsonb")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Origen")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MetadatosRawJsonb");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MetadatosRawJsonb"), "gin");

                    b.HasIndex("ProveedorId");

                    b.ToTable("FacturasProveedores");
                });

            modelBuilder.Entity("Core.Entities.Inquilino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfiguracionAtributosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfiguracionRegional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfiguracionTallesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RubroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subdominio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RubroId");

                    b.ToTable("Inquilinos");
                });

            modelBuilder.Entity("Core.Entities.Inventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StockDefectuoso")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StockRevision")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("Core.Entities.ItemComprobante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("ComprobanteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("IvaAlicuota")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<Guid>("VarianteProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ComprobanteId");

                    b.ToTable("ItemsComprobante");
                });

            modelBuilder.Entity("Core.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("Core.Entities.LogFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Accion")
                        .HasColumnType("integer");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LogsFiscales");
                });

            modelBuilder.Entity("Core.Entities.MetodoPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiereAprobacionAdmin")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("MetodosPago", (string)null);
                });

            modelBuilder.Entity("Core.Entities.ModuloSuscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ModuloKey")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ModulosSuscripcion");
                });

            modelBuilder.Entity("Core.Entities.MovimientoSaldoCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DeudaOrigenId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MetodoPagoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VentaAsociadaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VentaIdAsociada")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("VentaAsociadaId");

                    b.ToTable("MovimientosSaldosClientes");
                });

            modelBuilder.Entity("Core.Entities.PagoProveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MetodoPagoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("PagosProveedores");
                });

            modelBuilder.Entity("Core.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ean13")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsFraccionable")
                        .HasColumnType("boolean");

                    b.Property<string>("EscalaTalles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadatosJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("numeric");

                    b.Property<string>("Temporada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoProducto")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MetadatosJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MetadatosJson"), "gin");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Core.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CondicionIva")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NombreFantasia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PorcentajeRecargo")
                        .HasColumnType("numeric");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Core.Entities.ProveedorProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("VendorSku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("ProveedoresProductos");
                });

            modelBuilder.Entity("Core.Entities.Rubro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("DiccionarioJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EsquemaMetadatosJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rubros");
                });

            modelBuilder.Entity("Core.Entities.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsDepositoCentral")
                        .HasColumnType("boolean");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Core.Entities.TelemetriaUso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Año")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<int>("Metrica")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TelemetriasUso");
                });

            modelBuilder.Entity("Core.Entities.TransaccionBilletera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BilleteraVirtualId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComprobanteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TransaccionesBilleteras");
                });

            modelBuilder.Entity("Core.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PinCodeHash")
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Core.Entities.VarianteProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AtributosJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrecioOverride")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Talle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AtributosJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AtributosJson"), "gin");

                    b.HasIndex("ProductId");

                    b.ToTable("VariantesProducto");
                });

            modelBuilder.Entity("Core.Entities.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CAE")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DescuentoGlobalPct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DescuentoMonto")
                        .HasColumnType("numeric");

                    b.Property<int>("EstadoVenta")
                        .HasColumnType("integer");

                    b.Property<string>("IdentificadorTicket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("MetodoPagoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("RecargoGlobalPct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RecargoMonto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("VencimientoCAE")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TenantId", "IdentificadorTicket")
                        .IsUnique();

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("Core.Entities.VentaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AlicuotaIvaPct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostoUnitarioAplicado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoIvaTotal")
                        .HasColumnType("numeric");

                    b.Property<bool>("PosibleDevolucion")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrecioUnitarioAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SubtotalLinea")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VarianteProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VarianteProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("VentasDetalles", (string)null);
                });

            modelBuilder.Entity("Core.Entities.ArqueoCajaDetalle", b =>
                {
                    b.HasOne("Core.Entities.ArqueoCaja", "ArqueoCaja")
                        .WithMany("Detalles")
                        .HasForeignKey("ArqueoCajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArqueoCaja");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("Core.Entities.Categoria", b =>
                {
                    b.HasOne("Core.Entities.Categoria", "Parent")
                        .WithMany("Subcategorias")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Core.Entities.ChequeTercero", b =>
                {
                    b.HasOne("Core.Entities.PagoProveedor", "PagoProveedor")
                        .WithMany("ChequesEntregados")
                        .HasForeignKey("PagoProveedorId");

                    b.Navigation("PagoProveedor");
                });

            modelBuilder.Entity("Core.Entities.ClientePrendaEnCurso", b =>
                {
                    b.HasOne("Core.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.VarianteProducto", "VarianteProducto")
                        .WithMany()
                        .HasForeignKey("VarianteProductoId");

                    b.Navigation("Cliente");

                    b.Navigation("VarianteProducto");
                });

            modelBuilder.Entity("Core.Entities.DistribucionPagoFactura", b =>
                {
                    b.HasOne("Core.Entities.FacturaProveedor", "FacturaProveedor")
                        .WithMany("DistribucionesPago")
                        .HasForeignKey("FacturaProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.PagoProveedor", "PagoProveedor")
                        .WithMany("DistribucionesFacturas")
                        .HasForeignKey("PagoProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacturaProveedor");

                    b.Navigation("PagoProveedor");
                });

            modelBuilder.Entity("Core.Entities.FacturaProveedor", b =>
                {
                    b.HasOne("Core.Entities.Proveedor", "Proveedor")
                        .WithMany("Facturas")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Core.Entities.Inquilino", b =>
                {
                    b.HasOne("Core.Entities.Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("Core.Entities.Inventario", b =>
                {
                    b.HasOne("Core.Entities.VarianteProducto", "VarianteProducto")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VarianteProducto");
                });

            modelBuilder.Entity("Core.Entities.ItemComprobante", b =>
                {
                    b.HasOne("Core.Entities.Comprobante", null)
                        .WithMany("Items")
                        .HasForeignKey("ComprobanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.MetodoPago", b =>
                {
                    b.HasOne("Core.Entities.Inquilino", "Inquilino")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("Core.Entities.MovimientoSaldoCliente", b =>
                {
                    b.HasOne("Core.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId");

                    b.HasOne("Core.Entities.Venta", "VentaAsociada")
                        .WithMany()
                        .HasForeignKey("VentaAsociadaId");

                    b.Navigation("Cliente");

                    b.Navigation("MetodoPago");

                    b.Navigation("VentaAsociada");
                });

            modelBuilder.Entity("Core.Entities.PagoProveedor", b =>
                {
                    b.HasOne("Core.Entities.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodoPago");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Core.Entities.Producto", b =>
                {
                    b.HasOne("Core.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Core.Entities.ProveedorProducto", b =>
                {
                    b.HasOne("Core.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Proveedor", "Proveedor")
                        .WithMany("ProductosSuministrados")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Core.Entities.VarianteProducto", b =>
                {
                    b.HasOne("Core.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Core.Entities.Venta", b =>
                {
                    b.HasOne("Core.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Core.Entities.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.Inquilino", "Inquilino")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Inquilino");

                    b.Navigation("MetodoPago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Core.Entities.VentaDetalle", b =>
                {
                    b.HasOne("Core.Entities.VarianteProducto", "VarianteProducto")
                        .WithMany()
                        .HasForeignKey("VarianteProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VarianteProducto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Core.Entities.ArqueoCaja", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Core.Entities.Categoria", b =>
                {
                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("Core.Entities.Comprobante", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Core.Entities.FacturaProveedor", b =>
                {
                    b.Navigation("DistribucionesPago");
                });

            modelBuilder.Entity("Core.Entities.PagoProveedor", b =>
                {
                    b.Navigation("ChequesEntregados");

                    b.Navigation("DistribucionesFacturas");
                });

            modelBuilder.Entity("Core.Entities.Proveedor", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("ProductosSuministrados");
                });

            modelBuilder.Entity("Core.Entities.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
